# Makfile for compiling SASS files

SS = sass

all: vars-mixins.scss navbar.scss index.scss index.scss about.scss recipes-list.scss recipe.scss
	$(SS) style.scss ../css/style.css
	rm ../css/style.css.map
